### ISSUE TITLE
Gateway ID from MAC error

### ISSUE THREAD

**Issue by dlarue** [things4u/ESP-1ch-Gateway-v2.0#2]
There's a leading zero error in the Gateway ID/EUI. In my fork for the USA I fixed it with the following:

``````
```
``````

Serial.print("Gateway ID: ");
    char buf[16];
    WiFi.macAddress(MAC_array);
    sprintf(buf, "%02x%02x%02xffff%02x%02x%02x", \
        MAC_array[0],MAC_array[1],MAC_array[2],MAC_array[3],MAC_array[4],MAC_array[5]);
    Serial.print(buf);

```
The bug can be found in ESP-sc-gway20.ino and also in _wwwServer.ino
```

**Comment by platenspeler** [comment]
Thanks, I have fixed this in version 3 on the github now.
