### ISSUE TITLE
ArduinoJson library empty/corrupted

### ISSUE THREAD

**Issue by jpmeijers** [things4u/ESP-1ch-Gateway-v2.0#5]
As said in title, check the ArduinoJson library in your repo. It seems corrupted.

**Comment by platenspeler** [comment]
I will have a look. Since I'm using this at home as well something must have gone wrong during upload to github.

**Comment by platenspeler** [comment]
Can you please tell me what you think is missing or wrong, I can not see the problem yet on my side.

**Comment by jpmeijers** [comment]
For example this file:
https://github.com/things4u/ESP-1ch-Gateway-v2.0/blob/master/libraries/ArduinoJson/library.properties
is empty.

**Comment by platenspeler** [comment]
:-) Thanks!
Yep. Strange enough sourceTree does not complain about it and thinks that the last file is already at the destination. Apparently the length of the file or content is not checked.

**Comment by platenspeler** [comment]
I have manually copied the directory again to the sourceTree distribution directory. Only the library.properties file was now recognized to have changed. I have updated that file on github. Although I updated the complete directory no other files were found that needed staging.

**Comment by platenspeler** [comment]
As still some files were not OK, I have re-uploaded all ArduinoJson library files.
